// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApiReq struct {
	Action               *string  `protobuf:"bytes,1,req,name=action" json:"action,omitempty"`
	Method               *string  `protobuf:"bytes,2,req,name=method" json:"method,omitempty"`
	SystemId             *string  `protobuf:"bytes,3,req,name=systemId" json:"systemId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiReq) Reset()         { *m = ApiReq{} }
func (m *ApiReq) String() string { return proto.CompactTextString(m) }
func (*ApiReq) ProtoMessage()    {}
func (*ApiReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *ApiReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiReq.Unmarshal(m, b)
}
func (m *ApiReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiReq.Marshal(b, m, deterministic)
}
func (m *ApiReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiReq.Merge(m, src)
}
func (m *ApiReq) XXX_Size() int {
	return xxx_messageInfo_ApiReq.Size(m)
}
func (m *ApiReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiReq.DiscardUnknown(m)
}

var xxx_messageInfo_ApiReq proto.InternalMessageInfo

func (m *ApiReq) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

func (m *ApiReq) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *ApiReq) GetSystemId() string {
	if m != nil && m.SystemId != nil {
		return *m.SystemId
	}
	return ""
}

type ApiResp struct {
	Code                 *int32   `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg               *string  `protobuf:"bytes,2,req,name=errmsg" json:"errmsg,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiResp) Reset()         { *m = ApiResp{} }
func (m *ApiResp) String() string { return proto.CompactTextString(m) }
func (*ApiResp) ProtoMessage()    {}
func (*ApiResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *ApiResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiResp.Unmarshal(m, b)
}
func (m *ApiResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiResp.Marshal(b, m, deterministic)
}
func (m *ApiResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiResp.Merge(m, src)
}
func (m *ApiResp) XXX_Size() int {
	return xxx_messageInfo_ApiResp.Size(m)
}
func (m *ApiResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApiResp proto.InternalMessageInfo

func (m *ApiResp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *ApiResp) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

func (m *ApiResp) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ApiReq)(nil), "protobuf.apiReq")
	proto.RegisterType((*ApiResp)(nil), "protobuf.apiResp")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69,
	0x4a, 0x21, 0x5c, 0x6c, 0x89, 0x05, 0x99, 0x41, 0xa9, 0x85, 0x42, 0x62, 0x5c, 0x6c, 0x89, 0xc9,
	0x25, 0x99, 0xf9, 0x79, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0x9c, 0x41, 0x50, 0x1e, 0x48, 0x3c, 0x37,
	0xb5, 0x24, 0x23, 0x3f, 0x45, 0x82, 0x09, 0x22, 0x0e, 0xe1, 0x09, 0x49, 0x71, 0x71, 0x14, 0x57,
	0x16, 0x97, 0xa4, 0xe6, 0x7a, 0xa6, 0x48, 0x30, 0x83, 0x65, 0xe0, 0x7c, 0x25, 0x4f, 0x2e, 0x76,
	0xb0, 0xa9, 0xc5, 0x05, 0x42, 0x42, 0x5c, 0x2c, 0xc9, 0xf9, 0x29, 0xa9, 0x60, 0x43, 0x59, 0x83,
	0xc0, 0x6c, 0x90, 0x91, 0xa9, 0x45, 0x45, 0xb9, 0xc5, 0xe9, 0x30, 0x23, 0x21, 0x3c, 0x90, 0xda,
	0x94, 0xc4, 0x92, 0x44, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x30, 0x1b, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x72, 0x23, 0x5d, 0x63, 0xba, 0x00, 0x00, 0x00,
}
